version: '3.6'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - 5433:5432
    volumes:
      - app_data:/var/lib/postgresql/data
    env_file:
      - postgres.env

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak_container
    env_file:
      keycloak.env
    command: start-dev
    depends_on:
      - keycloak_db
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - 8090:8080

  keycloak_db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      keycloak_postgres.env

volumes:
  postgres_data:
  keycloak_data:
  app_data:


