spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client_id}
            client-secret: ${client_secret}
            redirect-uri: http://localhost:3000/
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${issuer_uri}
            jwk-set-uri: ${jwk-set-uri}
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/LibraryAppRealm/protocol/openid-connect/certs
  config:
    import: file:env.properties