spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  security:

    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client_id}
            client-secret: ${client_secret}
            redirect-uri: http://localhost:3000/get-access-token-by-code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${issuer_uri}
            jwk-set-uri: ${jwk-set-uri}
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk-set-uri}
  config:
    import: file:env.properties
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        security: trace